# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IPFirstTest.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Kaman(object):
    def setupUi(self, Kaman):
        Kaman.setObjectName("Kaman")
        Kaman.resize(800, 600)
        Kaman.setMinimumSize(QtCore.QSize(800, 600))
        Kaman.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(Kaman)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(230, 10, 3, 61))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 207, 48))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.IP_label = QtWidgets.QLabel(self.widget)
        self.IP_label.setTextFormat(QtCore.Qt.PlainText)
        self.IP_label.setObjectName("IP_label")
        self.gridLayout.addWidget(self.IP_label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.r_label = QtWidgets.QLabel(self.widget)
        self.r_label.setTextFormat(QtCore.Qt.PlainText)
        self.r_label.setObjectName("r_label")
        self.gridLayout.addWidget(self.r_label, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(30, 80, 186, 18))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.widget1)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.wholeword_Box = QtWidgets.QCheckBox(self.widget1)
        self.wholeword_Box.setObjectName("wholeword_Box")
        self.horizontalLayout.addWidget(self.wholeword_Box)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(240, 10, 77, 166))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.find_Button = QtWidgets.QPushButton(self.widget2)
        self.find_Button.setObjectName("find_Button")
        self.verticalLayout.addWidget(self.find_Button)
        self.replace_Button = QtWidgets.QPushButton(self.widget2)
        self.replace_Button.setObjectName("replace_Button")
        self.verticalLayout.addWidget(self.replace_Button)
        self.replace_Button_2 = QtWidgets.QPushButton(self.widget2)
        self.replace_Button_2.setObjectName("replace_Button_2")
        self.verticalLayout.addWidget(self.replace_Button_2)
        spacerItem = QtWidgets.QSpacerItem(17, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.OK_Button = QtWidgets.QPushButton(self.widget2)
        self.OK_Button.setWhatsThis("")
        icon = QtGui.QIcon.fromTheme("wd")
        self.OK_Button.setIcon(icon)
        self.OK_Button.setIconSize(QtCore.QSize(16, 16))
        self.OK_Button.setObjectName("OK_Button")
        self.verticalLayout.addWidget(self.OK_Button)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(120, 110, 91, 58))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.syntaxcomboBox = QtWidgets.QComboBox(self.widget3)
        self.syntaxcomboBox.setObjectName("syntaxcomboBox")
        self.syntaxcomboBox.addItem("")
        self.syntaxcomboBox.addItem("")
        self.syntaxcomboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.syntaxcomboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        Kaman.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Kaman)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuCopyright_yusengo = QtWidgets.QMenu(self.menubar)
        self.menuCopyright_yusengo.setObjectName("menuCopyright_yusengo")
        Kaman.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Kaman)
        self.statusbar.setObjectName("statusbar")
        Kaman.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCopyright_yusengo.menuAction())
        self.IP_label.setBuddy(self.lineEdit)
        self.r_label.setBuddy(self.lineEdit_2)
        self.label.setBuddy(self.syntaxcomboBox)

        self.retranslateUi(Kaman)
        self.OK_Button.clicked.connect(Kaman.close)
        QtCore.QMetaObject.connectSlotsByName(Kaman)
        Kaman.setTabOrder(self.lineEdit, self.find_Button)
        Kaman.setTabOrder(self.find_Button, self.lineEdit_2)
        Kaman.setTabOrder(self.lineEdit_2, self.replace_Button)
        Kaman.setTabOrder(self.replace_Button, self.replace_Button_2)
        Kaman.setTabOrder(self.replace_Button_2, self.checkBox)
        Kaman.setTabOrder(self.checkBox, self.wholeword_Box)
        Kaman.setTabOrder(self.wholeword_Box, self.syntaxcomboBox)
        Kaman.setTabOrder(self.syntaxcomboBox, self.OK_Button)

    def retranslateUi(self, Kaman):
        _translate = QtCore.QCoreApplication.translate
        Kaman.setWindowTitle(_translate("Kaman", "MainWindow"))
        self.IP_label.setText(_translate("Kaman", "Find and &Search"))
        self.r_label.setText(_translate("Kaman", "Replace"))
        self.checkBox.setText(_translate("Kaman", "&CaseSensitive"))
        self.wholeword_Box.setText(_translate("Kaman", "&wholeWord"))
        self.find_Button.setText(_translate("Kaman", "Find"))
        self.replace_Button.setText(_translate("Kaman", "Replace"))
        self.replace_Button_2.setText(_translate("Kaman", "Replace &All"))
        self.OK_Button.setText(_translate("Kaman", "我爱国家"))
        self.label.setText(_translate("Kaman", "&Syntax"))
        self.syntaxcomboBox.setItemText(0, _translate("Kaman", "hha"))
        self.syntaxcomboBox.setItemText(1, _translate("Kaman", "ahh"))
        self.syntaxcomboBox.setItemText(2, _translate("Kaman", "hah"))
        self.menuCopyright_yusengo.setTitle(_translate("Kaman", "copyright@yusengo"))

